### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by smackem** [smackem/zlang#1]
- [x] Function/method calls
- [x] Control flow
- [x] Format security (ZL): checksums, prefix check
- [x] More info for ZL header
  - [x] Register count
  - [x] Move stack frame memory (registers) into main memory
- [x] Reference counting
  - [x] `AddRef` and `RemoveRef` support in zln
  - [x] Emit `AddRef` and `RemoveRef` in compiler
  - [x] Lifetime tests
  - [x] Allocation strategy
  - [x] Allocation tests
- ~Replace reference counting with explicit allocation~
  - ~`use` bindings that free resources when out of scope (only allow on function level, not nested)~
  - ~`remote` keyword for struct fields: remote refs are not freed when the containing struct is freed~
- [x] .zap files
  - [x] .zap output for compiler
  - [x] .zap input for zl executable
- [x] Strings
  - [x] Loading
  - [x] Length
  - [x] Indexing
  - [x] Comparison
  - [x] Character translation in parser
  - [x] Concatenation
  - [x] Indexing
  - [x] `new string(byte[])` ctor
- [x] Runtime errors (panic)
- [ ] Debug info
  - [ ] Program debug segment
  - [ ] Stack traces on error
  - [x] `log` statement
  - [x] `assert` statement
- [ ] Misc
  - [ ] Safer `byte[]` to `string` conversion
  - [ ] allow return value of main function
  - [ ] pass runtime options like debug output to lib
- [x] Interfaces
  - [x] Check implementations in compiler
  - [x] `Callvirt` opcode for dynamic dispatch
  - [x] Interface tests
- [x] Built-in aggregate types
  - [x] list
- [ ] More list features
  - [x] indexing with `[ ]`
  - [x] Iterablility with `for in`
  - [x] `new list(array)` ctor
  - [ ] `list.addArray` and `list.addList` methods
  - [ ] `list.toArray method`
  - [ ] `list.sort` method
- [x] Runtime type checking (`is` operator)
- [x] Unions
  - [x] Emit as struct with flag field
  - [x] untyped fields:
         `union Choice { yes, no }`
- [ ] Enums
  - [ ] emit as typed integers
  - [ ] panic on conversion from int to enum
  - [ ] support `is` keyword for enums
- [ ] More assignment operators: `+=`, `-=` etc.
- [x] More literal formats
  - [x] Hex literals `0xacdc`,
  - [x] Literals have smallest possible type (byte for 0..255)
- [ ] Switch
  - [x] `switch` over union fields
  - [ ] `switch` as statement
  - [ ] `switch` over enum
- [x] Block expressions with `yield`
- [ ] Mutable types
- [x] Visibility rules
  - [x] Aggregate type instance creation
  - [x] Field access (read and write)
  - [x] Variable access
- [ ] IR Optimizations
  - [ ] Remove `NOP`
  - [ ] Remove `MOV` where redundant
  - [ ] Replace `LDC_xxx 0` with `LDC_ZERO`
  - [ ] Emit StringCache (global variable for each string loaded with `LDC_STR`)
  - [ ] Replace `LDC_Zero -> EQ_xxx` with `EQ_ZERO`
  - [ ] Map all bindings in switch over union to the same local variable
- [ ] More control flow
  - [ ] break
  - [ ] continue
  - [ ] `do .. until` loop
- [x] Intermediate JavaFX IDE
- [ ] CLI Compiler
- [ ] Port to Xtext
- [ ] Runtime library
  - [x] Base Interfaces
    - [x] Equatable
    - [x] Comparable
    - [x] `Objects.sort`, `Objects.equals`
  - [x] Boxing
  - [ ] Date and Time
  - [x] Strings
    - [x] itoa, ftoa, atoi, ftoi
  - [ ] Math
  - [x] Collections: Map, Set
  - [ ] Files
  - [ ] Sockets
  - [ ] Images (libpng)
